#!/bin/bash

function version() {
    cd $1
    version=$( git describe )
    if ! git diff-index --quiet HEAD --
    then
        version="${version}*"
    fi
    echo $version
}

export KALEIDOSCOPE_DIR=~/src/Kaleidoscope
kaleidoscope_version=$( version $KALEIDOSCOPE_DIR )

keymap_version=$( version . )

version="${kaleidoscope_version}::${keymap_version}"

# compile
# flash
make "$@" LOCAL_CFLAGS="-DBUILD_INFORMATION=\"$version\""
